import type { TileProduct } from '../types'

const ALL_TILES: TileProduct[] = [
  {
    id: 'hd-001',
    name: 'Restore Bright White 3x6 Ceramic Subway Wall Tile',
    brand: 'Daltile',
    retailer: 'Home Depot',
    price: 0.49,
    priceUnit: 'sqft',
    priceDisplay: '$0.49/sq ft',
    size: '3x6 in',
    material: 'Ceramic',
    finish: 'Glossy',
    color: 'White',
    imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&q=80',
    productUrl: 'https://www.homedepot.com',
    rating: 4.7,
    reviewCount: 2341,
    inStock: true,
    description: 'Classic white subway tile perfect for kitchen backsplashes and bathroom walls.',
    coverage: '11 sq ft per box',
    thickness: '5/16 in',
  },
  {
    id: 'fd-001',
    name: 'Calacatta Gold Marble Look Porcelain Floor & Wall Tile',
    brand: 'Happy Floors',
    retailer: 'Floor & Decor',
    price: 3.29,
    priceUnit: 'sqft',
    priceDisplay: '$3.29/sq ft',
    size: '12x24 in',
    material: 'Porcelain',
    finish: 'Polished',
    color: 'White',
    imageUrl: 'https://images.unsplash.com/photo-1581430872221-d1cfed785922?w=400&q=80',
    productUrl: 'https://www.flooranddecor.com',
    rating: 4.8,
    reviewCount: 876,
    inStock: true,
    description: 'Luxurious Calacatta marble look with gold veining — the designer look at a fraction of the price.',
    coverage: '15.6 sq ft per box',
    thickness: '3/8 in',
  },
  {
    id: 'tb-001',
    name: 'Carrara White Hexagon Marble Mosaic Tile',
    brand: 'MSI',
    retailer: 'Tile Bar',
    price: 9.49,
    priceUnit: 'sqft',
    priceDisplay: '$9.49/sq ft',
    size: '2x2 in hex',
    material: 'Natural Stone',
    finish: 'Polished',
    color: 'White',
    imageUrl: 'https://images.unsplash.com/photo-1617850687395-620757feb1f3?w=400&q=80',
    productUrl: 'https://www.tilebar.com',
    rating: 4.6,
    reviewCount: 432,
    inStock: true,
    description: 'Classic Carrara marble hexagon mosaic, ideal for bathroom floors and shower walls.',
    coverage: '5 sq ft per sheet',
    thickness: '1/4 in',
  },
  {
    id: 'lw-001',
    name: 'Charcoal Slate Gray Porcelain Floor Tile',
    brand: 'American Olean',
    retailer: "Lowe's",
    price: 1.99,
    priceUnit: 'sqft',
    priceDisplay: '$1.99/sq ft',
    size: '18x18 in',
    material: 'Porcelain',
    finish: 'Textured',
    color: 'Gray',
    imageUrl: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=400&q=80',
    productUrl: 'https://www.lowes.com',
    rating: 4.4,
    reviewCount: 1203,
    inStock: true,
    description: 'Durable charcoal porcelain tile with a natural slate texture for a modern, industrial look.',
    coverage: '18 sq ft per box',
    thickness: '3/8 in',
  },
  {
    id: 'fd-002',
    name: 'Ashen Wood Look Porcelain Plank Tile',
    brand: 'Emser',
    retailer: 'Floor & Decor',
    price: 3.79,
    priceUnit: 'sqft',
    priceDisplay: '$3.79/sq ft',
    size: '6x36 in',
    material: 'Porcelain',
    finish: 'Matte',
    color: 'Brown',
    imageUrl: 'https://images.unsplash.com/photo-1515263487990-61b07816b324?w=400&q=80',
    productUrl: 'https://www.flooranddecor.com',
    rating: 4.9,
    reviewCount: 654,
    inStock: true,
    description: 'Realistic wood grain porcelain plank — waterproof and scratch resistant, perfect for any room.',
    coverage: '12 sq ft per box',
    thickness: '3/8 in',
  },
  {
    id: 'wf-001',
    name: 'Azure Blue Glass Mosaic Backsplash Tile',
    brand: 'Abolos',
    retailer: 'Wayfair',
    price: 13.99,
    priceUnit: 'sqft',
    priceDisplay: '$13.99/sq ft',
    size: '1x1 in',
    material: 'Glass',
    finish: 'Glossy',
    color: 'Blue',
    imageUrl: 'https://images.unsplash.com/photo-1600585152220-90363fe7e115?w=400&q=80',
    productUrl: 'https://www.wayfair.com',
    rating: 4.3,
    reviewCount: 287,
    inStock: true,
    description: 'Vibrant azure blue glass mosaic tiles perfect for kitchen backsplashes and pool surrounds.',
    coverage: '5 sq ft per sheet',
    thickness: '3/16 in',
  },
  {
    id: 'tb-002',
    name: 'Absolute Black Matte Porcelain Floor Tile',
    brand: 'Marazzi',
    retailer: 'Tile Bar',
    price: 5.49,
    priceUnit: 'sqft',
    priceDisplay: '$5.49/sq ft',
    size: '24x24 in',
    material: 'Porcelain',
    finish: 'Matte',
    color: 'Black',
    imageUrl: 'https://images.unsplash.com/photo-1617850687395-620757feb1f3?w=400&q=80',
    productUrl: 'https://www.tilebar.com',
    rating: 4.7,
    reviewCount: 318,
    inStock: true,
    description: 'Sophisticated matte black large-format porcelain tile for dramatic floors and feature walls.',
    coverage: '16 sq ft per box',
    thickness: '1/2 in',
  },
  {
    id: 'hd-002',
    name: 'Terracotta Look Ceramic Floor Tile',
    brand: 'Style Selections',
    retailer: 'Home Depot',
    price: 1.49,
    priceUnit: 'sqft',
    priceDisplay: '$1.49/sq ft',
    size: '8x8 in',
    material: 'Ceramic',
    finish: 'Matte',
    color: 'Terracotta',
    imageUrl: 'https://images.unsplash.com/photo-1600585152220-90363fe7e115?w=400&q=80',
    productUrl: 'https://www.homedepot.com',
    rating: 4.2,
    reviewCount: 892,
    inStock: true,
    description: 'Classic terracotta look ceramic tile inspired by Mediterranean architecture.',
    coverage: '10 sq ft per box',
    thickness: '5/16 in',
  },
  {
    id: 'msi-001',
    name: 'White Penny Round Marble Mosaic',
    brand: 'MSI',
    retailer: 'MSI Surfaces',
    price: 10.99,
    priceUnit: 'sqft',
    priceDisplay: '$10.99/sq ft',
    size: '1 in round',
    material: 'Natural Stone',
    finish: 'Polished',
    color: 'White',
    imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&q=80',
    productUrl: 'https://www.msisurfaces.com',
    rating: 4.5,
    reviewCount: 203,
    inStock: false,
    description: 'Timeless white Thassos marble penny round mosaic, a classic choice for shower floors.',
    coverage: '5 sq ft per sheet',
    thickness: '1/4 in',
  },
  {
    id: 'lw-002',
    name: 'Travertine Look Porcelain Floor Tile',
    brand: 'American Olean',
    retailer: "Lowe's",
    price: 2.49,
    priceUnit: 'sqft',
    priceDisplay: '$2.49/sq ft',
    size: '12x12 in',
    material: 'Porcelain',
    finish: 'Satin',
    color: 'Beige',
    imageUrl: 'https://images.unsplash.com/photo-1581430872221-d1cfed785922?w=400&q=80',
    productUrl: 'https://www.lowes.com',
    rating: 4.3,
    reviewCount: 567,
    inStock: true,
    description: 'Natural travertine look porcelain with warm beige tones — the durability of porcelain with the beauty of stone.',
    coverage: '10 sq ft per box',
    thickness: '3/8 in',
  },
  {
    id: 'fd-003',
    name: 'Concrete Gray Large Format Porcelain Tile',
    brand: 'Emser',
    retailer: 'Floor & Decor',
    price: 4.49,
    priceUnit: 'sqft',
    priceDisplay: '$4.49/sq ft',
    size: '24x48 in',
    material: 'Porcelain',
    finish: 'Matte',
    color: 'Gray',
    imageUrl: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=400&q=80',
    productUrl: 'https://www.flooranddecor.com',
    rating: 4.6,
    reviewCount: 441,
    inStock: true,
    description: 'Ultra-large format concrete look porcelain tile for a seamless, modern aesthetic.',
    coverage: '16 sq ft per box',
    thickness: '1/2 in',
  },
  {
    id: 'hd-003',
    name: 'Peel and Stick White Subway Tile Backsplash',
    brand: 'Smart Tiles',
    retailer: 'Home Depot',
    price: 8.97,
    priceUnit: 'piece',
    priceDisplay: '$8.97/piece',
    size: '10.95x9.7 in',
    material: 'Glass',
    finish: 'Glossy',
    color: 'White',
    imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&q=80',
    productUrl: 'https://www.homedepot.com',
    rating: 4.0,
    reviewCount: 3201,
    inStock: true,
    description: 'Easy peel-and-stick backsplash tile — no grout, no mess, no professional needed.',
    coverage: '0.74 sq ft per sheet',
  },
  {
    id: 'tb-003',
    name: 'Sage Green Zellige Handmade Ceramic Tile',
    brand: 'Cle Tile',
    retailer: 'Tile Bar',
    price: 22.99,
    priceUnit: 'sqft',
    priceDisplay: '$22.99/sq ft',
    size: '4x4 in',
    material: 'Ceramic',
    finish: 'Glossy',
    color: 'Green',
    imageUrl: 'https://images.unsplash.com/photo-1600585152220-90363fe7e115?w=400&q=80',
    productUrl: 'https://www.tilebar.com',
    rating: 4.9,
    reviewCount: 145,
    inStock: false,
    description: 'Artisan handmade Moroccan Zellige tile with a rich, irregular glaze — each tile is unique.',
    coverage: '8 sq ft per box',
    thickness: '5/16 in',
  },
  {
    id: 'wf-002',
    name: 'Midnight Navy 2x8 Ceramic Subway Tile',
    brand: 'Merola Tile',
    retailer: 'Wayfair',
    price: 3.49,
    priceUnit: 'sqft',
    priceDisplay: '$3.49/sq ft',
    size: '2x8 in',
    material: 'Ceramic',
    finish: 'Glossy',
    color: 'Blue',
    imageUrl: 'https://images.unsplash.com/photo-1617850687395-620757feb1f3?w=400&q=80',
    productUrl: 'https://www.wayfair.com',
    rating: 4.5,
    reviewCount: 623,
    inStock: true,
    description: 'Deep navy subway tile with a rich, bold glaze — a modern twist on a classic shape.',
    coverage: '8 sq ft per box',
    thickness: '5/16 in',
  },
  {
    id: 'msi-002',
    name: 'Bianco Carrara 12x12 Marble Floor Tile',
    brand: 'MSI',
    retailer: 'MSI Surfaces',
    price: 7.99,
    priceUnit: 'sqft',
    priceDisplay: '$7.99/sq ft',
    size: '12x12 in',
    material: 'Natural Stone',
    finish: 'Polished',
    color: 'White',
    imageUrl: 'https://images.unsplash.com/photo-1581430872221-d1cfed785922?w=400&q=80',
    productUrl: 'https://www.msisurfaces.com',
    rating: 4.7,
    reviewCount: 389,
    inStock: true,
    description: 'Classic Italian Carrara marble with characteristic grey veining — timeless elegance.',
    coverage: '10 sq ft per box',
    thickness: '3/8 in',
  },
  {
    id: 'hd-004',
    name: 'Take Home Beige 12x12 Ceramic Floor Tile',
    brand: 'Daltile',
    retailer: 'Home Depot',
    price: 0.99,
    priceUnit: 'sqft',
    priceDisplay: '$0.99/sq ft',
    size: '12x12 in',
    material: 'Ceramic',
    finish: 'Satin',
    color: 'Beige',
    imageUrl: 'https://images.unsplash.com/photo-1515263487990-61b07816b324?w=400&q=80',
    productUrl: 'https://www.homedepot.com',
    rating: 4.1,
    reviewCount: 4523,
    inStock: true,
    description: 'Versatile beige ceramic floor tile — an affordable classic for kitchens and bathrooms.',
    coverage: '10 sq ft per box',
    thickness: '5/16 in',
  },
  {
    id: 'fd-004',
    name: 'Midnight Black Stacked Stone Mosaic',
    brand: 'Stonepeak',
    retailer: 'Floor & Decor',
    price: 14.99,
    priceUnit: 'sqft',
    priceDisplay: '$14.99/sq ft',
    size: '1x4 in',
    material: 'Natural Stone',
    finish: 'Textured',
    color: 'Black',
    imageUrl: 'https://images.unsplash.com/photo-1617850687395-620757feb1f3?w=400&q=80',
    productUrl: 'https://www.flooranddecor.com',
    rating: 4.4,
    reviewCount: 178,
    inStock: true,
    description: 'Dramatic stacked slate mosaic in deep black tones — stunning for accent walls and fireplaces.',
    coverage: '5 sq ft per sheet',
    thickness: '3/4 in',
  },
  {
    id: 'lw-003',
    name: 'White 4x16 Ceramic Subway Wall Tile',
    brand: 'Style Selections',
    retailer: "Lowe's",
    price: 1.19,
    priceUnit: 'sqft',
    priceDisplay: '$1.19/sq ft',
    size: '4x16 in',
    material: 'Ceramic',
    finish: 'Glossy',
    color: 'White',
    imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&q=80',
    productUrl: 'https://www.lowes.com',
    rating: 4.3,
    reviewCount: 1876,
    inStock: true,
    description: 'Modern elongated subway tile in classic white — perfect for contemporary bathroom remodels.',
    coverage: '10 sq ft per box',
    thickness: '5/16 in',
  },
  {
    id: 'tb-004',
    name: 'Warm Sand Porcelain 6x6 Pool Tile',
    brand: 'Porcelanosa',
    retailer: 'Tile Bar',
    price: 6.99,
    priceUnit: 'sqft',
    priceDisplay: '$6.99/sq ft',
    size: '6x6 in',
    material: 'Porcelain',
    finish: 'Textured',
    color: 'Beige',
    imageUrl: 'https://images.unsplash.com/photo-1600585152220-90363fe7e115?w=400&q=80',
    productUrl: 'https://www.tilebar.com',
    rating: 4.6,
    reviewCount: 231,
    inStock: true,
    description: 'Slip-resistant textured porcelain tile rated for pool surrounds, patios, and wet areas.',
    coverage: '11.11 sq ft per box',
    thickness: '3/8 in',
  },
  {
    id: 'wf-003',
    name: 'Antique French Pattern Travertine Tile',
    brand: 'MSI',
    retailer: 'Wayfair',
    price: 5.99,
    priceUnit: 'sqft',
    priceDisplay: '$5.99/sq ft',
    size: 'Pattern mix',
    material: 'Natural Stone',
    finish: 'Tumbled',
    color: 'Beige',
    imageUrl: 'https://images.unsplash.com/photo-1581430872221-d1cfed785922?w=400&q=80',
    productUrl: 'https://www.wayfair.com',
    rating: 4.5,
    reviewCount: 312,
    inStock: false,
    description: 'Authentic travertine in the classic French pattern (Versailles) — timeless old-world elegance.',
    coverage: '10 sq ft per box',
    thickness: '1/2 in',
  },
  {
    id: 'hd-005',
    name: 'Grigio Gray 12x24 Porcelain Floor Tile',
    brand: 'MSI',
    retailer: 'Home Depot',
    price: 2.29,
    priceUnit: 'sqft',
    priceDisplay: '$2.29/sq ft',
    size: '12x24 in',
    material: 'Porcelain',
    finish: 'Matte',
    color: 'Gray',
    imageUrl: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=400&q=80',
    productUrl: 'https://www.homedepot.com',
    rating: 4.5,
    reviewCount: 1432,
    inStock: true,
    description: 'Popular gray porcelain in a versatile 12x24 format — works in modern and transitional designs.',
    coverage: '15.6 sq ft per box',
    thickness: '3/8 in',
  },
  {
    id: 'msi-003',
    name: 'Onyx Nero Marquina Black Marble Tile',
    brand: 'MSI',
    retailer: 'MSI Surfaces',
    price: 12.99,
    priceUnit: 'sqft',
    priceDisplay: '$12.99/sq ft',
    size: '12x24 in',
    material: 'Natural Stone',
    finish: 'Polished',
    color: 'Black',
    imageUrl: 'https://images.unsplash.com/photo-1617850687395-620757feb1f3?w=400&q=80',
    productUrl: 'https://www.msisurfaces.com',
    rating: 4.8,
    reviewCount: 197,
    inStock: true,
    description: 'Dramatic black marble with striking white veining — a bold statement for floors and feature walls.',
    coverage: '15.6 sq ft per box',
    thickness: '3/8 in',
  },
  {
    id: 'fd-005',
    name: 'Blanco White 3D Wave Pattern Ceramic Tile',
    brand: 'Daltile',
    retailer: 'Floor & Decor',
    price: 4.79,
    priceUnit: 'sqft',
    priceDisplay: '$4.79/sq ft',
    size: '4x8 in',
    material: 'Ceramic',
    finish: 'Glossy',
    color: 'White',
    imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&q=80',
    productUrl: 'https://www.flooranddecor.com',
    rating: 4.6,
    reviewCount: 263,
    inStock: true,
    description: 'Sculptural 3D wave ceramic tile adding tactile texture to any wall — eye-catching and unique.',
    coverage: '8.72 sq ft per box',
    thickness: '7/16 in',
  },
  {
    id: 'lw-004',
    name: 'Oyster Shell 12x24 Porcelain Wall Tile',
    brand: 'Marazzi',
    retailer: "Lowe's",
    price: 2.99,
    priceUnit: 'sqft',
    priceDisplay: '$2.99/sq ft',
    size: '12x24 in',
    material: 'Porcelain',
    finish: 'Satin',
    color: 'Beige',
    imageUrl: 'https://images.unsplash.com/photo-1515263487990-61b07816b324?w=400&q=80',
    productUrl: 'https://www.lowes.com',
    rating: 4.4,
    reviewCount: 521,
    inStock: true,
    description: 'Soft oyster-toned porcelain with a subtle satin finish — neutral and versatile.',
    coverage: '15.6 sq ft per box',
    thickness: '3/8 in',
  },
  {
    id: 'tb-005',
    name: 'Forest Fern Green 2x10 Ceramic Tile',
    brand: 'Fireclay Tile',
    retailer: 'Tile Bar',
    price: 18.99,
    priceUnit: 'sqft',
    priceDisplay: '$18.99/sq ft',
    size: '2x10 in',
    material: 'Ceramic',
    finish: 'Glossy',
    color: 'Green',
    imageUrl: 'https://images.unsplash.com/photo-1600585152220-90363fe7e115?w=400&q=80',
    productUrl: 'https://www.tilebar.com',
    rating: 4.7,
    reviewCount: 89,
    inStock: false,
    description: 'Hand-glazed forest green ceramic subway tile — made in the USA with sustainable practices.',
    coverage: '6.4 sq ft per box',
    thickness: '3/8 in',
  },
  {
    id: 'hd-006',
    name: 'Smoke Ash Hexagon Porcelain Mosaic Floor Tile',
    brand: 'Daltile',
    retailer: 'Home Depot',
    price: 3.99,
    priceUnit: 'sqft',
    priceDisplay: '$3.99/sq ft',
    size: '6x6 in hex',
    material: 'Porcelain',
    finish: 'Matte',
    color: 'Gray',
    imageUrl: 'https://images.unsplash.com/photo-1617850687395-620757feb1f3?w=400&q=80',
    productUrl: 'https://www.homedepot.com',
    rating: 4.5,
    reviewCount: 734,
    inStock: true,
    description: 'On-trend hexagon mosaic in muted ash tones — a chic choice for bathroom floors and wet areas.',
    coverage: '8.65 sq ft per box',
    thickness: '3/8 in',
  },
  {
    id: 'wf-004',
    name: 'Rustic Brown Saltillo Mexican Floor Tile',
    brand: 'Tierra y Fuego',
    retailer: 'Wayfair',
    price: 4.29,
    priceUnit: 'sqft',
    priceDisplay: '$4.29/sq ft',
    size: '12x12 in',
    material: 'Ceramic',
    finish: 'Matte',
    color: 'Terracotta',
    imageUrl: 'https://images.unsplash.com/photo-1515263487990-61b07816b324?w=400&q=80',
    productUrl: 'https://www.wayfair.com',
    rating: 4.2,
    reviewCount: 341,
    inStock: true,
    description: 'Traditional Mexican saltillo tile with warm rustic appeal — hand-formed and kiln-fired.',
    coverage: '10 sq ft per box',
    thickness: '1/2 in',
  },
]

export function getDemoTiles(query: string): TileProduct[] {
  if (!query || query.trim() === '') return ALL_TILES

  const terms = query.toLowerCase().split(/\s+/).filter(Boolean)

  const scored = ALL_TILES.map((tile) => {
    const haystack = [
      tile.name, tile.brand, tile.retailer, tile.material,
      tile.finish, tile.color, tile.size, tile.description ?? '',
    ].join(' ').toLowerCase()

    const score = terms.reduce((acc, term) => {
      if (haystack.includes(term)) return acc + 1
      return acc
    }, 0)

    return { tile, score }
  })

  const filtered = scored.filter(({ score }) => score > 0)
  if (filtered.length === 0) return ALL_TILES // return all if nothing matches

  return filtered
    .sort((a, b) => b.score - a.score)
    .map(({ tile }) => tile)
}
